version: "2.27"
services:
  # killing_game_backend:
  #   build: .
  #   ports:
  #     - "8080:8080"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    volumes:
      - ./db/data/mysql-db:/var/lib/mysql
volumes:
  mysql-db:
